export const WRONG_DATA_TYPE = "WRONG_DATA_TYPE";
export const NO_ARGUMENTS_PASSED = "NO_ARGUMENTS_PASSED";
export const CANNOT_SAVE_VALUE_FOR_KEY = "CANNOT_SAVE_CONTENT_VALUE_FOR_KEY";
export const STORAGE_FILE_CORRUPTED = "STORAGE_FILE_CORRUPTED";
