export const WRONG_DATA_TYPE = "WRONG_DATA_TYPE";

export const NO_ARGUMENTS_PASSED = "NO_ARGUMENTS_PASSED";

export const CANNOT_SAVE_VALUE_FOR_KEY = "CANNOT_SAVE_CONTENT_VALUE_FOR_KEY";

export const UNKNOWN_ERROR = "UNKNOWN_ERROR";

export const CORRUPTED_STORAGE_FILE = "CORRUPTED_STORAGE_FILE";

export const USER_ACCEPTED_CORRUPTED_STORAGE_FILE =
  "USER_ACCEPTED_CORRUPTED_STORAGE_FILE";
